package com.woojoo.allsearching.constant

const val EXTRA_EMPTY_SEARCHING_KEYWORD = "EXTRA_EMPTY_SEARCHING_KEYWORD"
const val EXTRA_NETWORK_EXCEPTION = "EXTRA_NETWORK_EXCEPTION"

const val EXTRA_WEB_VIEW_MODEL = "EXTRA_WEB_VIEW_MODEL"